# Data paths
data:
  patents:
    raw_path: "data/raw/patents/"
    processed_path: "data/processed/patents.csv"
    ai_categories_path: "data/raw/categories/patent_categories.xlsx"
  onet:
    raw_path: "data/raw/onet/"
    task_ratings_path: "data/raw/onet/Task Ratings-3.xlsx"
    processed_path: "data/processed/onet_tasks.csv"
  
# Model configuration
embedding:
  model_name: "anferico/bert-for-patents"
  device: "cpu"  # "cuda" or "cpu"
  batch_size: 32
  max_length: 512
  normalize: true

# Matching configuration
matching:
  num_leaves: 200
  num_leaves_to_search: 100
  training_sample_size: 250000
  reorder_num_neighbors: 100
  pre_reorder_num_neighbors: 250
  anisotropic_quantization_threshold: 0.2
  
# Processing
processing:
  years_to_process: [2021, 2022, 2023, 2024, 2025]
  ai_topic_filter: 0  # Filter for AI patents
  similarity_threshold: 0.75
  top_k_matches: 200

# Output
output:
  results_path: "data/processed/matches/"
  format: "csv"  # or "parquet"
  save_embeddings: true